[2022-08-04 19:50:18,302] {processor.py:163} INFO - Started process (PID=40) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 19:50:18,306] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 19:50:18,309] {logging_mixin.py:109} INFO - [2022-08-04 19:50:18,308] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 19:50:18,316] {logging_mixin.py:109} INFO - [2022-08-04 19:50:18,314] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 19:50:18,360] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 19:50:18,383] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.087 seconds
[2022-08-04 19:50:48,545] {processor.py:163} INFO - Started process (PID=91) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 19:50:48,549] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 19:50:48,553] {logging_mixin.py:109} INFO - [2022-08-04 19:50:48,553] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 19:50:48,561] {logging_mixin.py:109} INFO - [2022-08-04 19:50:48,559] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 19:50:48,589] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 19:50:48,607] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.070 seconds
[2022-08-04 19:51:18,937] {processor.py:163} INFO - Started process (PID=143) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 19:51:18,939] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 19:51:18,940] {logging_mixin.py:109} INFO - [2022-08-04 19:51:18,940] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 19:51:18,947] {logging_mixin.py:109} INFO - [2022-08-04 19:51:18,945] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 19:51:18,992] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 19:51:19,018] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.089 seconds
[2022-08-04 19:51:50,015] {processor.py:163} INFO - Started process (PID=186) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 19:51:50,020] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 19:51:50,022] {logging_mixin.py:109} INFO - [2022-08-04 19:51:50,022] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 19:51:50,038] {logging_mixin.py:109} INFO - [2022-08-04 19:51:50,029] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 19:51:50,078] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 19:51:50,097] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.090 seconds
[2022-08-04 19:52:20,991] {processor.py:163} INFO - Started process (PID=238) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 19:52:20,993] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 19:52:20,994] {logging_mixin.py:109} INFO - [2022-08-04 19:52:20,994] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 19:52:20,998] {logging_mixin.py:109} INFO - [2022-08-04 19:52:20,997] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 19:52:21,020] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 19:52:21,032] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.046 seconds
[2022-08-04 19:52:53,848] {processor.py:163} INFO - Started process (PID=291) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 19:52:53,853] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 19:52:53,854] {logging_mixin.py:109} INFO - [2022-08-04 19:52:53,854] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 19:52:53,881] {logging_mixin.py:109} INFO - [2022-08-04 19:52:53,867] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 19:52:54,101] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 19:52:54,133] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.318 seconds
[2022-08-04 19:53:25,224] {processor.py:163} INFO - Started process (PID=344) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 19:53:25,235] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 19:53:25,239] {logging_mixin.py:109} INFO - [2022-08-04 19:53:25,238] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 19:53:25,268] {logging_mixin.py:109} INFO - [2022-08-04 19:53:25,261] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 19:53:25,350] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 19:53:25,379] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.179 seconds
[2022-08-04 19:58:48,478] {processor.py:163} INFO - Started process (PID=40) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 19:58:48,481] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 19:58:48,483] {logging_mixin.py:109} INFO - [2022-08-04 19:58:48,482] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 19:58:48,488] {logging_mixin.py:109} INFO - [2022-08-04 19:58:48,486] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 19:58:48,519] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 19:58:48,538] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.066 seconds
[2022-08-04 19:59:18,874] {processor.py:163} INFO - Started process (PID=94) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 19:59:18,881] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 19:59:18,882] {logging_mixin.py:109} INFO - [2022-08-04 19:59:18,882] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 19:59:18,898] {logging_mixin.py:109} INFO - [2022-08-04 19:59:18,894] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 19:59:18,974] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 19:59:19,000] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.158 seconds
[2022-08-04 19:59:49,137] {processor.py:163} INFO - Started process (PID=146) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 19:59:49,139] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 19:59:49,140] {logging_mixin.py:109} INFO - [2022-08-04 19:59:49,139] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 19:59:49,143] {logging_mixin.py:109} INFO - [2022-08-04 19:59:49,142] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 19:59:49,166] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 19:59:49,178] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.046 seconds
[2022-08-04 20:00:20,095] {processor.py:163} INFO - Started process (PID=196) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 20:00:20,100] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 20:00:20,103] {logging_mixin.py:109} INFO - [2022-08-04 20:00:20,103] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 20:00:20,133] {logging_mixin.py:109} INFO - [2022-08-04 20:00:20,119] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 20:00:20,229] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 20:00:20,275] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.202 seconds
[2022-08-04 20:00:50,551] {processor.py:163} INFO - Started process (PID=241) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 20:00:50,555] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 20:00:50,562] {logging_mixin.py:109} INFO - [2022-08-04 20:00:50,561] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 20:00:50,586] {logging_mixin.py:109} INFO - [2022-08-04 20:00:50,575] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 20:00:50,669] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 20:00:50,700] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.171 seconds
[2022-08-04 20:01:21,101] {processor.py:163} INFO - Started process (PID=293) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 20:01:21,108] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 20:01:21,111] {logging_mixin.py:109} INFO - [2022-08-04 20:01:21,110] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 20:01:21,128] {logging_mixin.py:109} INFO - [2022-08-04 20:01:21,120] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 20:01:21,167] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 20:01:21,184] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.110 seconds
[2022-08-04 20:01:51,671] {processor.py:163} INFO - Started process (PID=337) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 20:01:51,674] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 20:01:51,676] {logging_mixin.py:109} INFO - [2022-08-04 20:01:51,676] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 20:01:51,691] {logging_mixin.py:109} INFO - [2022-08-04 20:01:51,689] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 20:01:51,741] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 20:01:51,771] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.106 seconds
[2022-08-04 20:02:22,463] {processor.py:163} INFO - Started process (PID=390) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 20:02:22,466] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 20:02:22,469] {logging_mixin.py:109} INFO - [2022-08-04 20:02:22,469] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 20:02:22,483] {logging_mixin.py:109} INFO - [2022-08-04 20:02:22,479] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 20:02:22,521] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 20:02:22,548] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.094 seconds
[2022-08-04 20:02:52,723] {processor.py:163} INFO - Started process (PID=444) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 20:02:52,727] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 20:02:52,728] {logging_mixin.py:109} INFO - [2022-08-04 20:02:52,728] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 20:02:52,741] {logging_mixin.py:109} INFO - [2022-08-04 20:02:52,737] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 20:02:52,952] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 20:02:52,986] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.271 seconds
[2022-08-04 20:03:23,428] {processor.py:163} INFO - Started process (PID=487) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 20:03:23,440] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 20:03:23,444] {logging_mixin.py:109} INFO - [2022-08-04 20:03:23,443] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 20:03:23,502] {logging_mixin.py:109} INFO - [2022-08-04 20:03:23,455] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 20:03:23,568] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 20:03:23,592] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.182 seconds
[2022-08-04 20:03:54,656] {processor.py:163} INFO - Started process (PID=531) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 20:03:54,661] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 20:03:54,664] {logging_mixin.py:109} INFO - [2022-08-04 20:03:54,663] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 20:03:54,677] {logging_mixin.py:109} INFO - [2022-08-04 20:03:54,671] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 20:03:54,763] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 20:03:54,789] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.142 seconds
[2022-08-04 20:04:24,895] {processor.py:163} INFO - Started process (PID=580) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 20:04:24,898] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 20:04:24,899] {logging_mixin.py:109} INFO - [2022-08-04 20:04:24,899] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 20:04:24,906] {logging_mixin.py:109} INFO - [2022-08-04 20:04:24,904] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 20:04:24,935] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 20:04:24,952] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.064 seconds
[2022-08-04 20:04:54,982] {processor.py:163} INFO - Started process (PID=620) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 20:04:54,984] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 20:04:54,986] {logging_mixin.py:109} INFO - [2022-08-04 20:04:54,985] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 20:04:55,006] {logging_mixin.py:109} INFO - [2022-08-04 20:04:54,998] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 20:04:55,067] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 20:04:55,089] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.112 seconds
[2022-08-04 20:05:27,125] {processor.py:163} INFO - Started process (PID=672) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 20:05:27,129] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 20:05:27,130] {logging_mixin.py:109} INFO - [2022-08-04 20:05:27,130] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 20:05:27,180] {logging_mixin.py:109} INFO - [2022-08-04 20:05:27,153] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 20:05:27,302] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 20:05:27,324] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.207 seconds
[2022-08-04 20:05:57,345] {processor.py:163} INFO - Started process (PID=715) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 20:05:57,347] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 20:05:57,348] {logging_mixin.py:109} INFO - [2022-08-04 20:05:57,347] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 20:05:57,361] {logging_mixin.py:109} INFO - [2022-08-04 20:05:57,351] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 20:05:57,381] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 20:05:57,395] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.054 seconds
[2022-08-04 20:06:31,578] {processor.py:163} INFO - Started process (PID=767) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 20:06:31,605] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 20:06:31,616] {logging_mixin.py:109} INFO - [2022-08-04 20:06:31,614] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 20:06:31,783] {logging_mixin.py:109} INFO - [2022-08-04 20:06:31,733] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 20:06:33,979] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 20:06:34,057] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 2.583 seconds
[2022-08-04 20:07:04,830] {processor.py:163} INFO - Started process (PID=821) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 20:07:04,833] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 20:07:04,835] {logging_mixin.py:109} INFO - [2022-08-04 20:07:04,834] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 20:07:04,845] {logging_mixin.py:109} INFO - [2022-08-04 20:07:04,842] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 20:07:04,899] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 20:07:04,929] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.108 seconds
[2022-08-04 20:07:36,132] {processor.py:163} INFO - Started process (PID=864) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 20:07:36,135] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 20:07:36,136] {logging_mixin.py:109} INFO - [2022-08-04 20:07:36,136] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 20:07:36,150] {logging_mixin.py:109} INFO - [2022-08-04 20:07:36,141] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 20:07:36,187] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 20:07:36,239] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.113 seconds
[2022-08-04 20:08:08,367] {processor.py:163} INFO - Started process (PID=910) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 20:08:08,371] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 20:08:08,373] {logging_mixin.py:109} INFO - [2022-08-04 20:08:08,372] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 20:08:08,389] {logging_mixin.py:109} INFO - [2022-08-04 20:08:08,378] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 20:08:08,417] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 20:08:08,438] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.080 seconds
[2022-08-04 20:08:51,078] {processor.py:163} INFO - Started process (PID=962) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 20:08:51,082] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 20:08:51,084] {logging_mixin.py:109} INFO - [2022-08-04 20:08:51,084] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 20:08:51,113] {logging_mixin.py:109} INFO - [2022-08-04 20:08:51,100] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 20:08:51,190] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 20:08:51,217] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.151 seconds
[2022-08-04 20:09:21,630] {processor.py:163} INFO - Started process (PID=1015) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 20:09:21,634] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 20:09:21,635] {logging_mixin.py:109} INFO - [2022-08-04 20:09:21,634] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 20:09:21,643] {logging_mixin.py:109} INFO - [2022-08-04 20:09:21,639] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 20:09:21,672] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 20:09:21,686] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.061 seconds
[2022-08-04 20:09:51,824] {processor.py:163} INFO - Started process (PID=1057) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 20:09:51,826] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 20:09:51,826] {logging_mixin.py:109} INFO - [2022-08-04 20:09:51,826] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 20:09:51,834] {logging_mixin.py:109} INFO - [2022-08-04 20:09:51,831] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 20:09:51,877] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 20:09:51,889] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.068 seconds
[2022-08-04 20:10:22,385] {processor.py:163} INFO - Started process (PID=1108) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 20:10:22,387] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 20:10:22,388] {logging_mixin.py:109} INFO - [2022-08-04 20:10:22,388] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 20:10:22,394] {logging_mixin.py:109} INFO - [2022-08-04 20:10:22,392] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 20:10:22,431] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 20:10:22,444] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.064 seconds
[2022-08-04 20:10:52,686] {processor.py:163} INFO - Started process (PID=1160) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 20:10:52,689] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 20:10:52,691] {logging_mixin.py:109} INFO - [2022-08-04 20:10:52,691] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 20:10:52,705] {logging_mixin.py:109} INFO - [2022-08-04 20:10:52,701] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 20:10:52,783] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 20:10:52,809] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.134 seconds
[2022-08-04 20:11:26,240] {processor.py:163} INFO - Started process (PID=1203) to work on /opt/airflow/dags/my_dag.py
[2022-08-04 20:11:26,247] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-04 20:11:26,248] {logging_mixin.py:109} INFO - [2022-08-04 20:11:26,248] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-04 20:11:26,297] {logging_mixin.py:109} INFO - [2022-08-04 20:11:26,271] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-04 20:11:26,393] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-04 20:11:26,417] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.188 seconds
